smart_user:
    resource: "@SmartUserBundle/Resources/config/routing.yaml"

smart_file_upload:
    resource: "@SmartFileUploadBundle/Resources/config/routing.yaml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
